theme: "minima"


title: Gylang's Blog
author: Gylang Satria 
description: just a ordinary blogger
email: sayugiteam@gmail.com
#url: nanti ini ditambahkan

timezone: Etc/UTC # GitHub uses UTC. This is to force dev environment to match
future: false # GitHub Pages will publish future posts if this isn't set to false


# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out

#twitter_username: gylang_satria // udah jarang aktif juga
github_username: gylangsatria
instagram_username: gylang_satria
#linkedin_username: gylangsatriayudha
#facebook_username: username
#flickr_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username
rss: rss



kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
    values:
      image: "" # Apply default site image
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Other # Add a default tag to all posts
